[workspace]
members = [
    "wgui",
    "wui-lsp",
    "wui-derive",
    "zed-wui",
    "examples/allcomponents",
    "examples/puppychat",
    "examples/todo",
    "examples/todo_wui",
    "examples/three_demo",
    "examples/urdf"
]
