schema_version = 1
id = "wui"
name = "WUI"
version = "0.0.1"
description = "WUI language support"
authors = ["You"]
repository = ""

[language_servers.wui-lsp]
name = "WUI LSP"
languages = ["WUI"]

[grammars.wui]
repository = "https://github.com/J45k4/wgui.git"
path = "zed-wui/grammars/wui"
rev = "6b09b41bcc01a6a443d99985a5e39ca028d37419"
