schema_version = 1
id = "wui"
name = "WUI"
version = "0.0.1"
description = "WUI language support"
authors = ["You"]
repository = ""

[language_servers.wui-lsp]
name = "WUI LSP"
languages = ["WUI"]

[grammars.wui]
repository = "https://github.com/J45k4/wgui.git"
rev = "fc85818aa1e1c0cf703696b465e310e4d51f86d2"
path = "tree-sitter-wui"